# -*- coding: utf-8 -*-
# Build Calculator Functionality - PyQt5 GUI Thursdays # 8 9
# https://www.youtube.com/watch?v=YEOOcrm5ulA&list=PLCC34OHNcOtpmCA8s_dpPMvQLyHbvxocY&index=9
# 10:00

#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(715, 1118)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(20, 10, 681, 111))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.outputLabel.setFont(font)
        self.outputLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.outputLabel.setLineWidth(5)
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.precentBtn = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("%"))
        self.precentBtn.setGeometry(QtCore.QRect(20, 150, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.precentBtn.setFont(font)
        self.precentBtn.setObjectName("precentBtn")
        self.CBtn = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("C"))
        self.CBtn.setGeometry(QtCore.QRect(200, 150, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.CBtn.setFont(font)
        self.CBtn.setObjectName("CBtn")
        self.arrowBtn = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.remove_it())
        self.arrowBtn.setGeometry(QtCore.QRect(380, 150, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.arrowBtn.setFont(font)
        self.arrowBtn.setObjectName("arrowBtn")

        ############################
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("/"))
        self.pushButton_4.setGeometry(QtCore.QRect(550, 150, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.btn7 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("7"))
        self.btn7.setGeometry(QtCore.QRect(20, 320, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.btn7.setFont(font)
        self.btn7.setObjectName("btn7")
        self.Btn8 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("8"))

        self.Btn8.setGeometry(QtCore.QRect(200, 320, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Btn8.setFont(font)
        self.Btn8.setObjectName("Btn8")
        self.Btn9 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("9"))
        self.Btn9.setGeometry(QtCore.QRect(380, 320, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Btn9.setFont(font)
        self.Btn9.setObjectName("Btn9")
        self.BtnMul = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("*"))
        self.BtnMul.setGeometry(QtCore.QRect(550, 320, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.BtnMul.setFont(font)
        self.BtnMul.setObjectName("BtnMul")
        self.Btnplus = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("+"))
        self.Btnplus.setGeometry(QtCore.QRect(550, 660, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Btnplus.setFont(font)
        self.Btnplus.setObjectName("Btnplus")
        self.Btn3 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("3"))
        self.Btn3.setGeometry(QtCore.QRect(380, 660, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Btn3.setFont(font)
        self.Btn3.setObjectName("Btn3")

        self.Btn4 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("4"))

        self.Btn4.setGeometry(QtCore.QRect(20, 490, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Btn4.setFont(font)
        self.Btn4.setObjectName("Btn4")
        self.Btn5 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("5"))
        self.Btn5.setGeometry(QtCore.QRect(200, 490, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Btn5.setFont(font)
        self.Btn5.setObjectName("Btn5")
        self.Btn2 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("2"))
        self.Btn2.setGeometry(QtCore.QRect(200, 660, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Btn2.setFont(font)
        self.Btn2.setObjectName("Btn2")
        self.Btn1 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("1"))
        self.Btn1.setGeometry(QtCore.QRect(20, 660, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Btn1.setFont(font)
        self.Btn1.setObjectName("Btn1")
        self.Btn6 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("6"))
        self.Btn6.setGeometry(QtCore.QRect(380, 490, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Btn6.setFont(font)
        self.Btn6.setObjectName("Btn6")
        self.BtnMinus = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("-"))
        self.BtnMinus.setGeometry(QtCore.QRect(550, 490, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.BtnMinus.setFont(font)
        self.BtnMinus.setObjectName("BtnMinus")
        self.Btn0 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("0"))
        self.Btn0.setGeometry(QtCore.QRect(200, 830, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Btn0.setFont(font)
        self.Btn0.setObjectName("Btn0")
        self.BtnPM = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.plus_minus_it())
        self.BtnPM.setGeometry(QtCore.QRect(20, 830, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.BtnPM.setFont(font)
        self.BtnPM.setObjectName("BtnPM")
        self.BtnPoint = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.dot_it())
        self.BtnPoint.setGeometry(QtCore.QRect(380, 830, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.BtnPoint.setFont(font)
        self.BtnPoint.setObjectName("BtnPoint")
        self.BtnEqual = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.math_it())
        self.BtnEqual.setGeometry(QtCore.QRect(550, 830, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.BtnEqual.setFont(font)
        self.BtnEqual.setObjectName("BtnEqual")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 715, 56))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    ##############

    def math_it(self):
        try:
          screen = self.outputLabel.text()
          answer = eval(screen)# Calculate
          self.outputLabel.setText(str(answer))
        except:
            self.outputLabel.setText("Err")
    # remove one char from input number
    def remove_it(self):
        screen = self.outputLabel.text()
        screen = screen[:-1]  # remove last string
        self.outputLabel.setText(screen)

    def plus_minus_it(self):
        screen = self.outputLabel.text()
        if "-" in screen:
            self.outputLabel.setText(screen.replace("-",""))
        else:
            self.outputLabel.setText("-" + screen)
    def dot_it(self):
        screen = self.outputLabel.text()
        if screen[-1] == ".":  # if last char is '.'
            pass
        else:
            self.outputLabel.setText(screen + ".")

    def press_it(self, pressed):

        if pressed == "C":
            self.outputLabel.setText("0")
        else:

            if self.outputLabel.text() == "0":
                new_number = pressed
            else:

                new_number = self.outputLabel.text() + pressed
            self.outputLabel.setText(new_number)

    #########
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "calculator"))
        self.outputLabel.setText(_translate("MainWindow", "0"))
        self.precentBtn.setText(_translate("MainWindow", "%"))
        self.CBtn.setText(_translate("MainWindow", "C"))
        self.arrowBtn.setText(_translate("MainWindow", "<<"))
        self.pushButton_4.setText(_translate("MainWindow", "/"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.Btn8.setText(_translate("MainWindow", "8"))
        self.Btn9.setText(_translate("MainWindow", "9"))
        self.BtnMul.setText(_translate("MainWindow", "x"))
        self.Btnplus.setText(_translate("MainWindow", "+"))
        self.Btn3.setText(_translate("MainWindow", "3"))
        self.Btn4.setText(_translate("MainWindow", "4"))
        self.Btn5.setText(_translate("MainWindow", "5"))
        self.Btn2.setText(_translate("MainWindow", "2"))
        self.Btn1.setText(_translate("MainWindow", "1"))
        self.Btn6.setText(_translate("MainWindow", "6"))
        self.BtnMinus.setText(_translate("MainWindow", "-"))
        self.Btn0.setText(_translate("MainWindow", "0"))
        self.BtnPM.setText(_translate("MainWindow", "+/-"))
        self.BtnPoint.setText(_translate("MainWindow", "."))
        self.BtnEqual.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
