# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todolist2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1115, 1166)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.additem_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.additem_pushButton.setGeometry(QtCore.QRect(80, 150, 231, 81))
        self.additem_pushButton.setObjectName("additem_pushButton")
        self.deleteitem_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteitem_pushButton.setGeometry(QtCore.QRect(340, 150, 231, 81))
        self.deleteitem_pushButton.setObjectName("deleteitem_pushButton")
        self.clearAll_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearAll_pushButton.setGeometry(QtCore.QRect(600, 150, 241, 81))
        self.clearAll_pushButton.setObjectName("clearAll_pushButton")
        self.addItem_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.addItem_lineEdit.setGeometry(QtCore.QRect(70, 50, 1031, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.addItem_lineEdit.setFont(font)
        self.addItem_lineEdit.setText("")
        self.addItem_lineEdit.setObjectName("addItem_lineEdit")
        self.myList_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.myList_listWidget.setGeometry(QtCore.QRect(60, 250, 1041, 791))
        self.myList_listWidget.setObjectName("myList_listWidget")
        self.save_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.save_pushButton.setGeometry(QtCore.QRect(860, 150, 241, 81))
        self.save_pushButton.setObjectName("save_pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1115, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ToDoList"))
        self.additem_pushButton.setText(_translate("MainWindow", "Add"))
        self.deleteitem_pushButton.setText(_translate("MainWindow", "Delete"))
        self.clearAll_pushButton.setText(_translate("MainWindow", "Clear all"))
        self.save_pushButton.setText(_translate("MainWindow", "Save to DB"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
